import { collection, getDocs, updateDoc, doc, query, where } from 'firebase/firestore';
import { db } from '../firebase.js';

// 기존 일정 데이터에서 자동으로 생성된 설명 필드 정리
export const cleanupScheduleDescriptions = async () => {
  try {
    console.log('🧹 일정 설명 필드 정리 시작...');
    
    // schedules 컬렉션에서 모든 일정 데이터 가져오기
    const schedulesSnapshot = await getDocs(collection(db, 'schedules'));
    const schedules = schedulesSnapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
    
    console.log(`📊 총 ${schedules.length}개 일정 발견`);
    
    let updatedCount = 0;
    let skippedCount = 0;
    
    for (const schedule of schedules) {
      console.log(`🔍 일정 처리 중: ${schedule.text} (${schedule.id})`);
      
      // 설명 필드가 있고, 현장명과 동일하거나 자동 생성된 패턴인지 확인
      if (schedule.desc) {
        const desc = schedule.desc.toString().trim();
        const text = schedule.text.toString().trim();
        
        // 자동 생성된 설명 패턴들
        const autoGeneratedPatterns = [
          text, // 현장명과 동일
          `${text} - 진행중`,
          `${text} - 진행`,
          `${text} - 예정`,
          `${text} - 완료`,
          `${text} - 미정`,
          text.replace(/\s+/g, ''), // 공백 제거된 현장명
          text.split(' ')[0], // 현장명의 첫 번째 단어
        ];
        
        const isAutoGenerated = autoGeneratedPatterns.some(pattern => 
          desc === pattern || desc.includes(pattern)
        );
        
        if (isAutoGenerated) {
          try {
            // 설명 필드 제거
            await updateDoc(doc(db, 'schedules', schedule.id), {
              desc: '',
              updatedAt: new Date()
            });
            
            console.log(`  ✅ 자동 생성된 설명 제거: "${desc}"`);
            updatedCount++;
            
          } catch (error) {
            console.error(`  ❌ 설명 제거 실패: ${schedule.text}`, error);
          }
        } else {
          console.log(`  ⏭️ 수동 입력된 설명 유지: "${desc}"`);
          skippedCount++;
        }
      } else {
        console.log(`  ⏭️ 설명 필드 없음`);
        skippedCount++;
      }
    }
    
    console.log('🎉 일정 설명 필드 정리 완료!');
    console.log(`📊 결과:`);
    console.log(`  - 자동 생성된 설명 제거: ${updatedCount}개`);
    console.log(`  - 수동 입력된 설명 유지: ${skippedCount}개`);
    console.log(`  - 총 처리된 일정: ${updatedCount + skippedCount}개`);
    
    return {
      success: true,
      updatedCount,
      skippedCount,
      totalCount: schedules.length
    };
    
  } catch (error) {
    console.error('❌ 일정 설명 필드 정리 실패:', error);
    throw error;
  }
};

// 브라우저 콘솔에서 실행할 수 있도록 전역 함수로 등록
if (typeof window !== 'undefined') {
  window.cleanupScheduleDescriptions = cleanupScheduleDescriptions;
  console.log('🧹 cleanupScheduleDescriptions 함수가 전역에 등록되었습니다.');
  console.log('사용법: cleanupScheduleDescriptions()');
}

